### ISSUE TITLE
[question] luajit USE flag

### ISSUE THREAD

**Issue by archenroot** [gentoo/lua#1]
Hi, finally I found some Gentoo experts on LUA ecosystem, hope you can help.

I maintain overlay with Torch AI framework from Facebook written in LUA, I have about 20 packages in my overlay, which I plan to include later in official science overlay once they are stabilized, but would love to migrate all into your new eclass I found. Currently having issue with this package:
https://github.com/archenroot/gentoo-overlay/tree/master/dev-lua/torch-paths

But in general I have also question as per subject. I never understood well the difference between lua and luajit (enabled via USE flag), but I see you don't use this luajit at all... So what is the story behind?
See also some of my constructions :-)) :
```
local mycmakeargs=(
		"-DLUADIR=$($(tc-getPKG_CONFIG) --variable INSTALL_LMOD $(usex luajit 'luajit' 'lua'))"
		"-DLIBDIR=$($(tc-getPKG_CONFIG) --variable INSTALL_LIB $(usex luajit 'luajit' 'lua'))"
		"-DLUA_BINDIR=$($(tc-getPKG_CONFIG) --variable INSTALL_BIN $(usex luajit 'luajit' 'lua'))"
		"-DLUA_INCDIR=$($(tc-getPKG_CONFIG) --variable INSTALL_INC $(usex luajit 'luajit' 'lua'))"
		"-DLUA_LIBDIR=$($(tc-getPKG_CONFIG) --variable INSTALL_CMOD $(usex luajit 'luajit' 'lua'))"
		"-DSCRIPTS_DIR=$($(tc-getPKG_CONFIG) --variable INSTALL_BIN $(usex luajit 'luajit' 'lua'))"
		"-DLUALIB=`equery files luajit |grep lib64/libluajit | grep .so | awk 'NR==0; END{print}'`"
		"-DLUA=/usr/bin/luajit"
```

Any comments/hints welcomed.

**Comment by msva** [comment]
well, some people prefer to use luajit over PUC-Rio Lua because of... JIT (just-in-time compilation. See: https://en.wikipedia.org/wiki/Just-in-time_compilation ).
Most in-tree ebuilds that support luajit makes the trick similar to the quoted above.

Although, in lua overlay (in most cases) I don't use it, because of the fact I implemented `LUA_TARGETS`, so there is a way to detect it current target (means, the target, that portage builds package for at the time of performing the check) is luajit or not.

Although, for some packages it is still needed to have `luajit` use-flag because of some conditions (like, when it installs system "binaries" (lua scripts, that would be interpreted by the interpreter set in the shebang), so in that cases we need to ask users to explicitly set whether they want that scripts would be interpreted using `lua` (which can be luajit too, look for `eselect-lua`) or `luajit` (`eselect-luajit`) kind of interpreter.
